name: Preview Build

on:
  push:
    branches:
      - master  # triggers on pushes to main

jobs:
  build_android:
    name: Build Android Preview
    runs-on: ubuntu-latest
    steps:
      # Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login to Expo
      - name: Login to Expo
        uses: expo/expo-github-action@v5
        with:
          expo-token: ${{ secrets.EXPO_TOKEN }}
      # Install eas
      - name: Install EAS
        run: npm install -g eas-cli
      # Trigger the preview build
      - name: Trigger Android Preview Build
        run: |
          eas build \
            --platform android \
            --profile preview \
            --non-interactive
